


services:
  - name: My Portfolio
    env: python
    region: oregon
    branch: main
    buildCommand: "pip install -r requirements.txt && cd my-app && npm ci && npm run build && cd .. && python backend/manage.py collectstatic --noinput && python backend/manage.py migrate"
    startCommand: "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
    instanceType: starter
