"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import logging
from pathlib import Path
from urllib.parse import urlsplit
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Load secret key and debug from environment for production safety
def get_env_setting(name, default=None, required=False):
    val = os.environ.get(name, default)
    if required and (val is None or val == ''):
        raise ImproperlyConfigured(f"Set the {name} environment variable")
    return val

SECRET_KEY = get_env_setting('DJANGO_SECRET_KEY', default=None, required=False)

# DEBUG should be explicitly set to 'True' in development via env
DEBUG = get_env_setting('DJANGO_DEBUG', default='False') == 'True'

# If SECRET_KEY is not set, fall back in development; require it in production
if not SECRET_KEY:
    if DEBUG:
        # WARNING: this fallback should only be used for local development.
        SECRET_KEY = 'local-dev-secret-key--please-set-DJANGO_SECRET_KEY-in-prod'
    else:
        raise ImproperlyConfigured('Set the DJANGO_SECRET_KEY environment variable for production')

allowed = get_env_setting('DJANGO_ALLOWED_HOSTS', default=None)
if allowed:
    ALLOWED_HOSTS = [h.strip() for h in allowed.split(',') if h.strip()]
else:
    # In DEBUG allow localhost for local development
    if DEBUG:
        ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    else:
        # Quick fallback for fast production deploys: allow all hosts if env var is missing.
        # NOTE: This is a temporary, less-secure setting — replace with explicit hosts ASAP.
        ALLOWED_HOSTS = ['*']



# allow hosts for deployment
# // For local development, you might want to allow localhost
# cd C:\Users\admin\OneDrive\Desktop\Portfolio\my-app; npm install; npm run build
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        # Use DATABASE_URL env var (e.g. postgres) in production, fallback to sqlite for local dev
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# If a DATABASE_URL is provided (e.g. postgres://user:pass@host:port/dbname), parse it
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    # Use dj-database-url for robust parsing and support for SSL/query params
    try:
        import dj_database_url
    except ImportError:
        raise ImproperlyConfigured('dj-database-url is required to parse DATABASE_URL; add it to requirements')

    # Parse and set database config; require SSL in production unless explicitly disabled
    db_config = dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=not DEBUG)
    # Ensure ENGINE key exists
    if 'ENGINE' not in db_config:
        db_config['ENGINE'] = 'django.db.backends.postgresql'
    DATABASES['default'] = db_config


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/assets/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_CREDENTIALS = True
# In development allow the local React dev server; use booleans for this setting
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = ['http://localhost:5173']
else:
    CORS_ALLOW_ALL_ORIGINS = False

# In production, prefer explicit CORS origins via env var
if not DEBUG:
    cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS')
    if cors_origins:
        # Parse and sanitize origins: strip whitespace, remove trailing slashes
        # and strip any path component (origins should be scheme://host[:port])
        origins = []
        for origin in cors_origins.split(','):
            origin = origin.strip()
            if not origin:
                continue
            parsed = urlsplit(origin)
            # If path present (e.g., http://localhost:5173/), drop it and reconstruct origin
            if parsed.scheme and parsed.netloc:
                clean = f"{parsed.scheme}://{parsed.netloc}"
            elif parsed.netloc:
                # missing scheme, assume https
                clean = f"https://{parsed.netloc}"
            else:
                # fallback: strip trailing slash
                clean = origin.rstrip('/')
            origins.append(clean)
        CORS_ALLOW_ALL_ORIGINS = False
        CORS_ALLOWED_ORIGINS = origins

# Email configuration (example using console backend for development)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production, configure SMTP settings like below:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.your-email-provider.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = ''
# EMAIL_HOST_PASSWORD = ''
# DEFAULT_FROM_EMAIL =''
# DEFAULT_TO_EMAIL = ''


# Static files settings
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATICFILES_DIRS = [
    # Vite outputs production files to `dist/` with assets under `dist/assets`.
    # Also include the `dist` root in case some build files (index-*.js/css) are at the root.
    BASE_DIR.parent / 'my-app' / 'dist' / 'assets',
    BASE_DIR.parent / 'my-app' / 'dist',
]

TEMPLATES[0]['DIRS'] = [BASE_DIR.parent / 'my-app' / 'dist']

# Security settings recommended for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_CONTENT_TYPE_NOSNIFF = True